## Sample kibana.yml
server.name: kibana01
server.port: 5601
server.host: "0.0.0.0"

#elasticsearch.url: "https://192.168.25.63:9200"
elasticsearch.url: ${ELASTICSEARCH_URL}

# , 172.19.0.2-3, 10.6.253.228
#elasticsearch.url: "https://localhost:9200"
# WORKED - elasticsearch.url: "https://192.168.75.41:9200"

#First connection use elastic user or update kibana password
elasticsearch.username: "kibana"
elasticsearch.password: "changeme"

# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
server.ssl.enabled: true
server.ssl.certificate: ./certs/kibana01/kibana01.crt
server.ssl.key: ./certs/kibana01/kibana01.key

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files validate that your Elasticsearch backend uses the same key files.
#elasticsearch.ssl.certificate: ./certs/ca/ca.crt
#elasticsearch.ssl.key: ./certs/ca/ca.key

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
elasticsearch.ssl.certificateAuthorities: [ "./certs/ca/ca.crt" ]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
elasticsearch.ssl.verificationMode: none

elasticsearch.requestTimeout: 60000

#x-pack settings:
#https://www.elastic.co/guide/en/elastic-stack-overview/current/xpack-settings.html
xpack.security.enabled: true
xpack.monitoring.enabled: true
#xpack.monitoring.elasticsearch.url: ${ELASTICSEARCH_URL}
xpack.monitoring.kibana.collection.enabled: true
#xpack.monitoring.elasticsearch.ssl.certificateAuthorities: [ "./certs/ca/ca.crt" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.ml.enabled: true
