instances:
  - name: es01
    dns:
      - es01 
      - localhost
    ip:
      - 127.0.0.1
  - name: es02
    dns:
      - es02
      - localhost
    ip:
      - 127.0.0.1
  - name: es03
    dns:
      - es03
      - localhost
    ip:
      - 127.0.0.1
  - name: kibana01
    dns:
      - kibana01
      - localhost
    ip:
      - 127.0.0.1
  - name: kibana02
    dns:
      - kibana02
      - localhost
    ip:
      - 127.0.0.1